### ISSUE TITLE
Build in support for Apache and autorenewal

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-certbot#1]
Maybe just using something as simple as https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-14-04

**Comment by 030** [comment]
https://certbot.eff.org/#ubuntuxenial-apache

**Comment by tomasbedrich** [comment]
I have a little bit more flexible system for this, which would fit nicely here (also for #2): https://github.com/tomasbedrich/ansible-role-certbot-autorenew/blob/master/tasks/main.yml
