### ISSUE TITLE
Problem during deploy

### ISSUE THREAD

**Issue by tasselchof** [geerlingguy/ansible-role-certbot#106]
TASK [geerlingguy.certbot : Install Certbot.] **********************************************************************************************************************************************************
fatal: [p]: FAILED! => {"changed": false, "failures": [], "msg": "Depsolve Error occured: \n Problem: package certbot-1.3.0-3.el8.noarch requires python3-certbot = 1.3.0-3.el8, but none of the providers can be installed\n  - cannot install the best candidate for the job\n  - nothing provides python3-mock needed by python3-certbot-1.3.0-3.el8.noarch\n  - nothing provides python3.6dist(mock) needed by python3-certbot-1.3.0-3.el8.noarch", "rc": 1, "results": []}
	to retry, use: --limit @/home/env/domains/o/server.retry

**Comment by ericsysmin** [comment]
@tasselchof what OS?

**Comment by tasselchof** [comment]
Hi! CentOS 8.

**Comment by tasselchof** [comment]
I also think so - it's working well now.
