### ISSUE TITLE
Tries to enable repo on Fedora 32 meant for CentOS 8+

### ISSUE THREAD

**Issue by TheNeikos** [geerlingguy/ansible-role-certbot#110]
This commit: https://github.com/geerlingguy/ansible-role-certbot/commit/09c898663665deb8484484bb6fa7087ab973a358 has added an additional step which also gets executed on my fedora 32 server. 

It fails with:

```
fatal: [XXXXXX]: FAILED! => {
    "changed": false,
    "cmd": "dnf config-manager --set-enabled PowerTools\n",
    "delta": "0:00:00.215747",
    "end": "2020-05-20 10:49:50.364318",
    "rc": 1,
    "start": "2020-05-20 10:49:50.148571"
}

STDERR:

Error: No matching repo to modify: PowerTools.


MSG:

non-zero return code
```

Looking through the issue that spawned this problem (https://github.com/geerlingguy/ansible-role-certbot/issues/107) this was because of problems installing `python3-certbot` which does install just fine on Fedora 32. 

So I think this should be skipped on at least Fedora 32 (and maybe other?) versions.

**Comment by jonas-hagen** [comment]
Same problem here. Thanks for the fix @TheNeikos! I am looking forward to the merge.

**Comment by kharyam** [comment]
Just ran into this today, thanks @TheNeikos

**Comment by TheNeikos** [comment]
This is still open AFAIK

**Comment by geerlingguy** [comment]
Sorry about the delays; just merged the fix, and I should be able to get a new release out soon!
