### ISSUE TITLE
Add support for ACME servers other than Let's Encrypt

### ISSUE THREAD

**Issue by maxhoesel** [geerlingguy/ansible-role-certbot#130]
I am interested in running this role against a self-hosted ACME server instead of the official Let's Encrypt one.

Over the last few years, several projects have sprung up that deal with hosting an ACME server for a private/internal network. I'm currently working on setting up one in a testing environment using [this project](https://github.com/smallstep/certificates). Having the option to use this role with such a self-hosted ACME server would be very nice for automatically generating and renewing internal certificates for encrypting application traffic.

I'd be happy to implement this feature myself, assuming that it is desired. Looking at the [documentation available](https://smallstep.com/blog/private-acme-server/), it seems like adding this feature would require adding an environmental var (`REQUESTS_CA_BUNDLE`) to all certbot_script calls, as well as a `--server` parameter to the initial create command. Obviously, this feature should be disabled by default and toggle-able via a role default.

**Comment by Lazerbeak12345** [comment]
I also would like this feature, and depending on availability, may be able to implement this.

If LetsEncrypt is down for any reason, my certs for my entire infrastructure could expire. Authorizing two ACME providers and falling back to a different one unlikely to fail at the same time as LetsEncrypt is what I have in mind. The ability to have a non-LE ACME is a good starting point.
