### ISSUE TITLE
Task "Enable DNF module for CentOS 8+" fails [PowerTools|powertools]

### ISSUE THREAD

**Issue by agno01** [geerlingguy/ansible-role-certbot#143]
### Problem:

`certbot` Ansible role fails when enabling dnf module PowerTools:

```
TASK [geerlingguy.certbot : Enable DNF module for CentOS 8+.] ********************************************************************************************************************
fatal: [<redacted_hostname>]: FAILED! => changed=false
  cmd: |-
    dnf config-manager --set-enabled PowerTools
  delta: '0:00:00.365425'
  end: '2021-02-09 08:45:59.785283'
  msg: non-zero return code
  rc: 1
  start: '2021-02-09 08:45:59.419858'
  stderr: 'Error: No matching repo to modify: PowerTools.'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
  ```

### Environment:
CentOS Linux release 8.3.2011
Ansible 2.10.5
geerlingguy.certbot 3.1.0

### Cause:
Yum repoid of Power Tools has changed from `PowerTools` to `powertools`:

https://wiki.centos.org/Manuals/ReleaseNotes/CentOS8.2011#Major_Changes

### Possible fix:
Add check for `CentOS Linux release` version.

**Comment by steinbrueckri** [comment]
@agno01 It's fixed on the master, you can use the git commit as the reference instead of the tag. At least this is my workaround until @geerlingguy creates a new release.
