### ISSUE TITLE
Error enabling DNF modules

### ISSUE THREAD

**Issue by bzamaere** [geerlingguy/ansible-role-certbot#157]
Running into this issue:
TASK [geerlingguy.certbot : Enable DNF module for CentOS 8+.] ************************************************************************************************
fatal: [172.16.0.191]: FAILED! => {"changed": false, "cmd": "dnf config-manager --set-enabled powertools\n", "delta": "0:00:00.293489", "end": "2021-06-28 17:07:34.137045", "msg": "non-zero return code", "rc": 1, "start": "2021-06-28 17:07:33.843556", "stderr": "Error: No matching repo to modify: powertools.", "stderr_lines": ["Error: No matching repo to modify: powertools."], "stdout": "", "stdout_lines": []}

Looks like dnf wants "PowerTools" not "powertools".

**Comment by kaihei777** [comment]
mee too
