### ISSUE TITLE
Cloning certbot fails on subsequent runs

### ISSUE THREAD

**Issue by pmackay** [geerlingguy/ansible-role-certbot#17]
After installing on the 2nd run I get the `Clone Certbot into configured directory.` task failing with:

`Local modifications exist in repository (force=no).`

Is this because `certbot-auto` has been made executable? Should the git task use `force`?

**Comment by pmackay** [comment]
I have just noticed #16 which is great and answers this. When I tried that change locally though, I hit https://github.com/ansible/ansible-modules-core/issues/5504 which is an issue in ansible v2.2 but looks like should be fixed in v2.2.1.

**Comment by zx1986** [comment]
Ansible has module for Let's Encrypt:
https://docs.ansible.com/ansible/letsencrypt_module.html

**Comment by geerlingguy** [comment]
Yeah, this should be fixed now.
