### ISSUE TITLE
Install certbot with package manager

### ISSUE THREAD

**Issue by exploide** [geerlingguy/ansible-role-certbot#18]
While there might be a demand to install the latest certbot version directly from GitHub, personally I like to install as much software as possible from distribution's package management.

Would you accept a PR adding the possibility to configure if one wants to use git or package?

Rationale: Some might use Ansible to bootstrap their hosts but do not regularly execute Ansible afterwards nor use ansible-pull. In this case the cloned git repository is barely updated, even with `certbot_keep_updated: yes`. This is bad, especially when urgent security updates are required. A package from the distribution's package management is probably automatically updated by unattended-upgrades or dnf-automatic.

**Comment by geerlingguy** [comment]
Yes, definitely! In fact, that's the way I have things set up for many of my other roles (e.g. `git`, `ruby`, etc.). I think when I originally created the role, certbot wasn't even a thing yet (still called `letsencrypt`), and nobody had apt, yum, or dnf packages available.
