### ISSUE TITLE
Install from source is broken

### ISSUE THREAD

**Issue by Synchro** [geerlingguy/ansible-role-certbot#182]
The bot closed earlier reports of this ([certbot-auto no longer exists](https://github.com/geerlingguy/ansible-role-certbot/blob/fdba1c435251341af7fbdfc44b276daafdea632f/tasks/install-from-source.yml#L12)), but it's still broken. It was reported in #167 and a PR submitted in #168, but both have been ignored.

**Comment by declan-morris** [comment]
Just hit this same issue, looked at PR #168 and it seems like a reasonable fix, anyway this could get merged
