### ISSUE TITLE
setup-RedHat.yml

### ISSUE THREAD

**Issue by mprusov** [geerlingguy/ansible-role-certbot#190]
Probably the code:

>       - name: Enable DNF module for CentOS 8.3+.
>         shell: |
>           dnf config-manager --set-enabled powertools
>         register: dnf_module_enable
>         changed_when: false
> 
>         when: ansible_facts['distribution_version'] is version('8.3', '>=')
> 
>       - name: Enable DNF module for CentOS 8.0–8.2.
>         shell: |
>           dnf config-manager --set-enabled PowerTools
>         register: dnf_module_enable
>         changed_when: false
> 
>     when: ansible_facts['distribution_version'] is version('8.2', '<=')

should be:

>       - name: Enable DNF module for CentOS 8.3+.
>         shell: |
>           dnf config-manager --set-enabled powertools
>         register: dnf_module_enable
>         changed_when: false
>         when: ansible_facts['distribution_version'] is version('8.3', '>=')
> 
>       - name: Enable DNF module for CentOS 8.0–8.2.
>         shell: |
>           dnf config-manager --set-enabled PowerTools
>         register: dnf_module_enable
>         changed_when: false
>         when: ansible_facts['distribution_version'] is version('8.2', '<=')

?

**Comment by csuka** [comment]
Yes, I guess so too.  
And your title should be, setup-RedHat.yml 👯‍♂️

**Comment by StefanIGit** [comment]
That's why I add my "when"s on top under the name ;)
Anyway, any plans to support CentOS 9?
