### ISSUE TITLE
Improvement for crontab

### ISSUE THREAD

**Issue by avra911** [geerlingguy/ansible-role-certbot#26]
Hello,

Ability to add extra cronjob parameters would be nice, for example ` --pre-hook "service nginx stop" --post-hook "service nginx start"`.

Regards,
R

Edited: I sent a PR: https://github.com/geerlingguy/ansible-role-certbot/pull/27

**Comment by avra911** [comment]
ping @geerlingguy :)

**Comment by enricostano** [comment]
What about using `/etc/letsencrypt/renewal/your.domain.org.conf` to manage hooks instead? It seems more clean and flexible to me.

**Comment by avra911** [comment]
@enricostano that is a good point, I cannot imagine another way of needing it in the crontab without managing from the *.conf.

Thanks!

**Comment by enricostano** [comment]
@avra911 cool! could you please update https://github.com/geerlingguy/ansible-role-certbot/pull/27 accordingly?
