### ISSUE TITLE
Could not open lock file

### ISSUE THREAD

**Issue by allthesignals** [geerlingguy/ansible-role-certbot#59]
Hello,
I'm seeing: `E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)` from the "Install Certbot." task. Any thoughts? I don't understand what variables I need to set up. What is the lock file for? 

I'm using Ubuntu Xenial. 

Thanks!

**Comment by geerlingguy** [comment]
@allthesignals that means your user account doesn't have permissions. Add `become: yes` to this role's invocation or to the playbook and it should work fine.
