### ISSUE TITLE
certbot_create_command: wrong quotes since using folded block scalar syntax

### ISSUE THREAD

**Issue by mbiberhofer** [geerlingguy/ansible-role-certbot#61]
Since defaults/main.yml is using the '>' (folded block scalar, see https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html) syntax, one gets an error:

`TASK [geerlingguy.certbot : Generate new certificate if one doesn't exist.] ********************************************************************************************************************************************************************************************************************************************************************************
fatal: [xxx-xxx]: FAILED! => {"changed": true, "cmd": "\"certbot certonly --standalone --noninteractive --agree-tos --email xxx@xxx.xx -d xxx.xxx.xxx\"", "delta": "0:00:00.001942", "end": "2018-10-02 08:00:25.388877", "msg": "non-zero return code", "rc": 127, "start": "2018-10-02 08:00:25.386935", "stderr": "/bin/sh: 1: certbot certonly --standalone --noninteractive --agree-tos --email xxx@xxx.xx -d xxx.xxx.xxx: not found", "stderr_lines": ["/bin/sh: 1: certbot certonly --standalone --noninteractive --agree-tos --email infrastruktur@igniti.de -d igniti-xxx.xxx.xxx: not found"], "stdout": "", "stdout_lines": []} ` 

This is due to the quotes being migrated to the new syntax. Pull request with the change incoming.

Occurence verified with:
ansible version: 2.6.5
geerlingguy.nginx 3.1.0

Greetings,
Mario

**Comment by mDfRg** [comment]
Can confirm, switching to one-line syntax made it work again.
