### ISSUE TITLE
Basic config fails on servers without nginx

### ISSUE THREAD

**Issue by kokarn** [geerlingguy/ansible-role-certbot#65]
Hello!

I'm running into what I believe to be a an unexpected issue with the defaults for certs.

Running without `certbot_create_standalone_stop_services: []` fails on our CentOS 7 server not having nginx already installed with the message 
```
Could not find the requested service nginx: host
```

Is this intended behaviour?
I'd argue that it should by default not try to restart any service not provided by me.

**Comment by BusinessClick** [comment]
I think it should enough an existing condition for each service. 
Or override`certbot_create_standalone_stop_services` variable.
