### ISSUE TITLE
certbot_create_standalone_stop_services are only stopped at first run

### ISSUE THREAD

**Issue by wvh-github** [geerlingguy/ansible-role-certbot#67]
To solve this problem I have made 2 very simple templates for use as a pre and post hook.

/etc/letsencrypt/renewal-hooks/pre/stop_services:
```
#!/bin/bash

{% for item in certbot_create_standalone_stop_services %}
echo "stopping service {{ item }}"
{% if ansible_service_mgr == 'systemd' %}
systemctl stop {{ item }}
{% elif ansible_service_mgr == 'upstart' %}
initctl stop {{ item }}
{% elif ansible_service_mgr == 'openrc' %}
rc-service {{ item }} stop
{% else %}
service {{ item }} stop
{% endif %}
{% endfor %}

```
/etc/letsencrypt/renewal-hooks/post/start_services:
```
#!/bin/bash

{% for item in certbot_create_standalone_stop_services %}
echo "starting service {{ item }}"
{% if ansible_service_mgr == 'systemd' %}
systemctl start {{ item }}
{% elif ansible_service_mgr == 'upstart' %}
initctl start {{ item }}
{% elif ansible_service_mgr == 'openrc' %}
rc-service {{ item }} start
{% else %}
service {{ item }} start
{% endif %}
{% endfor %}

```
If wanted I could write a small patch to implement this and make it a little more robust.

**Comment by lnjX** [comment]
It were very cool if you could do so, I'm facing the same problem as you.

**Comment by speedlight** [comment]
I'm facing the same problem with nginx and apache servers

**Comment by colans** [comment]
This is still an issue.

**Comment by joeribekker** [comment]
With the addition of pre/post hooks in certbots renewal script, the solution posted here seems the best way to solve this: https://github.com/geerlingguy/ansible-role-certbot/pull/80#issuecomment-597532401

**Comment by colans** [comment]
This is still an issue.

**Comment by colans** [comment]
This is still an issue.

**Comment by colans** [comment]
This is still an issue.

**Comment by miili** [comment]
Well, these hooks look pretty straight forward. Why is this still an issue?

**Comment by colans** [comment]
:wave:

**Comment by geerlingguy** [comment]
I _hope_ #80 fixes the issue here—but if not, please reopen or open a new issue with more detail.
