### ISSUE TITLE
OSError: Command /opt/eff.org/certbot/venv/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 2

### ISSUE THREAD

**Issue by Booooooger** [geerlingguy/ansible-role-certbot#69]
when i run:

```
/certbot-auto renew  --no-self-upgrade --no-bootstrap
```

i got :
```
Requesting to rerun ./certbot-auto with root privileges...
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 988, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /opt/eff.org/certbot/venv/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 2

```
i've tried all ways in [certbot issue #2883](https://github.com/certbot/certbot/issues/2883). Such as

```
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
```
, @chani 's answer  and so on;

but ,they're  didn't work for me 

i guess it could be cause by using `/opt/eff.org/certbot/venv/bin/python2.7`, Could i change the default python2.7 path?  Perhaps，there are other solutions ?

Thanks!

**Comment by astrakid** [comment]
i have the same problem.

**Comment by robertolopezlopez** [comment]
I can reproduce this problem as well

**Comment by astrakid** [comment]
The problem disappeared the next day for me.

**Comment by xuyombo** [comment]
> The problem disappeared the next day for me.

**Comment by robertolopezlopez** [comment]
> I can reproduce this problem as well

I gave it a n-th try and also managed to get it working.

**Comment by johnstef99** [comment]
solved this problem by changing the default pip version!
1. check your pip and python version by typing `pip --version` and `python --version`.
2.if both of them aren't version 2.7 edit /.bashrc by typing `nano ~/.bashrc` and add: 
`alias pip='pip2' 
alias python='python2'`
these 2 lines at the top of the file
3. then type `source ~/.bashrc`
4. try to run cerbot command again and if it's not working try step 5
5. upgrade setuptools by typing `pip install --upgrade setuptools --user`

**Comment by bote100** [comment]
Step 5 doesn't helped!

**Comment by speedlight** [comment]
I had the same problem but in one run of the role everything start to wokr again :S wierd

**Comment by nise** [comment]
Sorry, 
I have the same problem. Some support for people not knowing python that much would be helpful.

**Comment by nise** [comment]
In my case pip was not installed. So I run `sudo apt-get install python-pip`, Then I tried to install `wheel` manually: `pip install wheel`. This failed because of missconfigured locals that could be fixed by the command `export LC_ALL=C`. After that I was able to run the certbot again.
