### ISSUE TITLE
Race condition issue with sever setup and certificate config/generation

### ISSUE THREAD

**Issue by fullofcaffeine** [geerlingguy/ansible-role-certbot#70]
Hi there!

Thanks for this role, it's very useful :)

I'm having a bit of a hard time trying to make my playbook completely idempotent when `certbot_create_standalone_stop_services` points to a web server. The problem I have is that the first time I set up the server, either the `geerlingguy.nginx` role fails because nginx can't find the certs (because the certbot role hasn't been run yet) or `geerlingguy.certbot` fails because it can't find nginx (because it hasn't been isntalled yet), depending on the order of execution of said roles.

It's easy to solve manually, of course: I removed the vhost def that included the path to the keyfiles from the yml and ran the playbook with roles in the following order:
- geerlingguy.nginx
- geerlingguy.certbot

This way, nginx doesn't complain about a non-existent file and the role runs succesfully, and the certbot role correctly generates the keys and then restarts nginx. I can then edit the playbook and add the reference to the keys after it runs the first time.

Another possibility would be to generate the certs before setting up the web server, but then I'd need to tell the certbot role to only restart nginx if the service is present. Must be something easy to do with ansible, but I'd like to check if there's a config option or if perhaps I'm using the role in the wrong way.

Am I missing something? Any insights appreciated!

**Comment by acro5piano** [comment]
I think you need to run certbot twice. For the first run, do not create cert by adding `certbot_create_if_missing: false` var. Next, install nginx, then run again `certbot_create_if_missing: true`.

**Comment by royalpudding** [comment]
This is still an issue. The Apache/Ngnix service won't start without a certificate and the certbot fails because the Apache/Nginx Service is not running.
