### ISSUE TITLE
OS-provided cronjob conflicts with role cronjob

### ISSUE THREAD

**Issue by Duologic** [geerlingguy/ansible-role-certbot#77]
So, Ubuntu (18.04 at least) installs a cronjob and makes use of renewal-hooks directories. I can't find much documentation about it, but there is a bug report here: https://bugs.launchpad.net/ubuntu/+source/python-certbot/+bug/1706409

There is some documentation on about the renewal-hooks directories:
https://certbot.eff.org/docs/using.html#renewing-certificates

I'm thinking about how I can tackle it, probably not install the cronjob from the role and simply install the hooks with a separate role for now, but may this can be handled by the role somehow.

Any ideas on this?

**Comment by wvh-github** [comment]
Please see PR #80 as it should resolve issues #67 
#55 and part of what you are describing. Please describe what part of the problem is not solved with my PR, so we can fix it. (I'm guess we don't need to create a cronjob on Ubuntu 18.04 but it would be nice if we'd know this for every supported distro.)

**Comment by Duologic** [comment]
PR #80 looks great, the renewal-hooks look like the way to go. I've looked for documentation about the cronjob on different distro's but didn't find much really.

In my experience, Ubuntu has a tendency to make choices _for_ the user, like installing a cronjob or auto-start service after installation, in case of configuration mgmnt this is not what you want. We could try to `stat` the file and if it exists don't install our own or as I do now: don't install the cronjob from the role `certbot_auto_renew: false`.

**Comment by tomasbedrich** [comment]
Don't close @stale_bot.. Still actual.

**Comment by gacallea** [comment]
still relevant.
