### ISSUE TITLE
Why is 'git clone' used instead of e.g. apt to install certbot?

### ISSUE THREAD

**Issue by 030** [geerlingguy/ansible-role-certbot#8]
According https://certbot.eff.org/#ubuntuxenial-nginx

```
sudo apt-get install letsencrypt 
```

and according https://certbot.eff.org/#centosrhel7-nginx

```
sudo yum install epel-release
sudo yum install certbot
```

**Comment by geerlingguy** [comment]
The git clone is easier to make work cross-platform at this point (it's been more consistent in my testing).

In the future, I may consider switching to default installing packages instead, but for now I would rather keep the slightly more stable route.
